"""Variants schema

Revision ID: 8031042b2442
Revises: bd5787ef0a03
Create Date: 2025-04-16 21:38:50.226326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8031042b2442'
down_revision: Union[str, None] = 'bd5787ef0a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('predecessor_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.internal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'images', ['internal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_table('variants')
    # ### end Alembic commands ###
